# Generated by Django 5.1.6 on 2025-03-14 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='game_images/'),
        ),
    ]
